# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Mihajlo Onboarding

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- task: Docker@2
- task: Docker@2
  inputs:
    containerRegistry: 'docker-hub-conn'
    repository: 'mihajlob2609/azure-webapp'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
  displayName: Build an image